//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAssignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Ticket_Game
    {
        public int Id { get; set; }
        public int Ticket_Game_Id { get; set; }
        public int OrderId { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Ticket_Game Ticket_Game { get; set; }
    }
}
