//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAssignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.Ticket_Game = new HashSet<Ticket_Game>();
        }
    
        public int Id { get; set; }
        public string Owner { get; set; }
        public int CategoryId { get; set; }
        public int Section { get; set; }
        public int Row { get; set; }
        public int Seat { get; set; }
        public string ViewUpload { get; set; }
    
        public virtual Ref_Category Ref_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket_Game> Ticket_Game { get; set; }
    }
}
