//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAssignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket_Game
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket_Game()
        {
            this.Order_Ticket_Game = new HashSet<Order_Ticket_Game>();
        }
    
        public int Id { get; set; }
        public int TicketId { get; set; }
        public int GameId { get; set; }
        public Nullable<double> Price { get; set; }
        public int Sold { get; set; }
        public int Configured { get; set; }
        public string Name { get; set; }
    
        public virtual Game Game { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Ticket_Game> Order_Ticket_Game { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
